import Head from "next/head";
import { Box, Button, Heading } from "@chakra-ui/react";
import { BsGoogle } from "react-icons/bs";
import { useGoogleSignIn } from "@/hooks/useGoogleSignIn";

export default function Home() {
  const { auth, signInWithGoogle, loading } = useGoogleSignIn();

  return (
    <>
      <Head>
        <title>Hashdex</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section>
        <Box>
          <Box py={"7rem"} bg={"ghostwhite"} textAlign={"center"}>
            <Heading mb={0}>Start moving pages around with Hashdex</Heading>
          </Box>
          <Button
            onClick={signInWithGoogle}
            leftIcon={<BsGoogle />}
            size={"lg"}
            my={"2rem"}
            mx={"auto"}
            display={"block"}
            colorScheme="purple"
            isDisabled={auth === null}
            isLoading={auth === null || loading}
          >
            Sign In with Google
          </Button>
        </Box>
      </section>
    </>
  );
}
